name = "gu"
version = "2.1.0"

description = "Zenity GUI dialogs Gleam wrapper"
licences = ["Apache-2.0"]
repository = {type = "github", user = "salif", repo = "gu"}

internal_modules = [
  "examples/*"
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
shellout = ">= 1.6.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"
