name = "gu"
version = "1.0.0"

description = "Zenity GUI dialogs Gleam wrapper"
licences = ["Apache-2.0"]
links = [{title = "Website", href = "https://github.com/salif/gu"}]
repository = {type = "github", user = "salif", repo = "gu"}

internal_modules = [
  "examples/*"
]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
shellout = "~> 1.6"

[dev-dependencies]
gleeunit = "~> 1.0"
